### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by kibernaut** [Loureas/anilibria-cli#1]
Hi. This is the error I get when running the script.

./anilibria-cli: 44: Syntax error: "(" unexpected

System is Ubuntu 22.04.

ЧЯДНТ?

**Comment by Loureas** [comment]
### Thanks for the feedback!

The problem was related to instructions that are not supported by the standard `SH` shell. Instead, the default improved `BASH` shell has been changed.
You can update the repository with the following command:
```sh
git pull
```
